name: "Publish next version to npm"

on:
  release:
    types: [prereleased]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci --no-progress
    - run: npm run build
    - run: npm version --no-push --no-git-tag-version --yes ${{ github.event.release.tag_name }}
    # Ensure npm 11.5.1 or later for trusted publishing
    - run: npm install -g npm@11.11.1
    - run: npm publish --tag next
